### PR TITLE
my first three files

### PR DESCRIPTION
**Pull request by SathiC1990**

### CODE REVIEW

**Review by ddobby94 — APPROVED** [review]
Nice work! :)

**Comment by hirenkumar91** [comment]
Great work, sathi

I can see you done whole assignment in one commit.
For practice i would suggest , make some changes in files and commit at all stage.
Make habit of using Git at every step of development.

keep up good work .

**Comment by SathiC1990** [comment]
> Nice work! :)


















> Great work, sathi
> 
> I can see you done whole assignment in one commit. For practice i would suggest , make some changes in files and commit at all stage. Make habit of using Git at every step of development.
> 
> keep up good work .

Hi mentors, I have done the changes . Can you please review it!

**Comment by HMTRIVEDI** [comment]
Super, 

For Future Assignments  " Before merging always wait for final review or  ask reviewer if you can merge , as it might be that reviewer, suggest more changes " 

Keep up the good work !

**Comment by hirenkumar91** [comment]
Super,

For Future Assignments i suggest 
" Before merging always wait for final review or ask reviewer if you can merge , as it might be that reviewer may suggest more changes "

Keep up the good work !

**Pull request merged**
